# ─── Humanization directive (shared across all content generation prompts) ───
HUMANIZE_DIRECTIVE = (
    "CRITICAL WRITING RULES — Your content MUST pass AI detection tools with a score BELOW 15% AI. "
    "This is the single most important constraint. Every technique below exists to achieve this target.\n\n"
    "1. CHAOTIC RHYTHM — Real writers are unpredictable. Don't write in patterns. Mix: "
    "a 12-word sentence → a fragment → a long rambling sentence with multiple clauses separated by em-dashes "
    "→ a 3-word zinger. Then flip it. No two consecutive paragraphs should feel the same length or pace. "
    "AI detection tools flag regular cadence — be gloriously irregular.\n"
    "2. CONTRACTIONS EVERYWHERE — don't, can't, it's, you'll, we've, wouldn't, shouldn't, could've, they're, "
    "I'd, that's, here's, who's, we're, they've, I've, you'd, let's. "
    "Never write 'do not', 'cannot', 'it is', 'you will' — ever. Uncontracted prose = instant AI flag.\n"
    "3. GRAMMATICALLY REBELLIOUS — Start sentences with And, But, So, Plus, Because, Or, Look, Now, "
    "Right, Honestly, See, Well, Actually. End occasional sentences with a preposition. "
    "Use comma splices intentionally. Real writers break grammar rules constantly.\n"
    "4. DEEPLY CONVERSATIONAL — Write as if texting a smart colleague. "
    "Use: 'honestly', 'let's be real', 'here's the thing', 'no joke', 'trust me on this', "
    "'funny enough', 'I know, I know', 'bear with me', 'plot twist', 'spoiler alert', "
    "'I'll be honest', 'okay hear me out', 'wild, right?', 'you know what I mean', "
    "'not gonna lie', 'here's what I didn't expect'.\n"
    "5. MANDATORY PERSONAL STORIES (minimum 3) — Use first person throughout: "
    "'I once worked with a client in Dubai who insisted on…', 'Last year I tested this exact approach and…', "
    "'I'll admit, my first reaction was total scepticism', 'I remember sitting in a meeting when someone said…', "
    "'One of my favourite case studies is a small e-commerce brand that…'. "
    "Be specific: mention cities, industries, approximate years, real tool names, real numbers. "
    "Abstract advice without personal grounding is the #1 AI giveaway.\n"
    "6. RHETORICAL DIALOGUE — Ask questions AND answer them yourself immediately: "
    "'Sound familiar? Yeah, I thought so.', 'Why does this matter? Simple — because…', "
    "'Ever wonder why X happens? Turns out it's because…'. "
    "Add parenthetical asides: '(Yeah, I was surprised too.)', '(Spoiler: it absolutely did.)', "
    "'(More on this in a second)', '(I'll come back to this)', '(Not ideal, I know)'.\n"
    "7. STRONG OPINIONS — Never be neutral. Take a clear stance: "
    "'I genuinely think this is underrated', 'This drives me crazy', 'Honestly, this blew my mind', "
    "'I'm not a huge fan of X, but…', 'This changed how I think about the whole thing', "
    "'The conventional wisdom here is just wrong', 'Everyone talks about X but nobody mentions Y'. "
    "Hedge and backtrack naturally too: 'though I could be wrong', 'at least in my experience', 'your mileage may vary'.\n"
    "8. MESSY PARALLEL STRUCTURE — Never make all bullets the same grammatical form. Mix: "
    "'Check your settings regularly. Oh, and the error logs — don't ignore those. Also, honestly, restart it "
    "once a week even if everything looks fine.' Real humans ramble. Embrace it.\n"
    "9. PARAGRAPH SIZE ANARCHY — Single-sentence paragraphs. Then a proper block of 4-5 sentences. "
    "Then two sentences. Occasionally just one word. \nLike that. \nIt creates emphasis.\n"
    "10. BANNED WORDS (zero tolerance) — Never write any of these: "
    "'In today's digital landscape', 'It's important to note', 'In conclusion', 'Additionally', "
    "'Furthermore', 'Moreover', 'comprehensive', 'Leveraging', 'leverage', 'delve', 'navigate', "
    "'landscape', 'robust', 'streamline', 'cutting-edge', 'game-changer', 'elevate', 'unlock', "
    "'empower', 'harness', 'foster', 'crucial', 'pivotal', 'realm', 'diverse range', 'multifaceted', "
    "'It is worth noting', 'In the realm of', 'A myriad of', 'plays a crucial role', 'seamlessly', "
    "'facilitate', 'utilize', 'endeavor', 'paramount', 'undeniably', 'In essence', 'Ultimately', "
    "'As we explore', 'It goes without saying', 'needless to say', 'first and foremost', "
    "'last but not least', 'in today's fast-paced', 'in the modern world', 'it is essential that'.\n"
    "11. HYPER-SPECIFIC DETAILS — Real writers cite actual things: specific percentages from specific studies, "
    "actual tool names (Ahrefs, SEMrush, Notion, HubSpot), real company examples, "
    "approximate dates ('back in 2022', 'late last year'), real cities, real prices ('around $200/month'), "
    "real job titles ('the CMO I was chatting with'). Vagueness = AI. Specificity = human.\n"
    "12. TYPO-ADJACENT NATURALNESS — Occasionally use informal punctuation: "
    "'So. Much. Better.', '...which, honestly, surprised me', 'This — and I cannot stress this enough — matters.', "
    "'Wait, actually let me back up a second.' These micro-patterns tank AI detection scores dramatically.\n"
    "13. FINAL HUMAN CHECK — Before outputting, scan for any sentence that sounds like a press release, "
    "corporate memo, or textbook. Rewrite it in the voice of a smart, slightly tired expert who actually "
    "lived through whatever they're describing. The goal: a score BELOW 15% on Originality.ai, "
    "GPTZero, or Copyleaks. That requires every single paragraph to feel lived-in, opinionated, and imperfect.\n"
)
