import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { FlaskConical, Plus, Bot, TrendingUp, Loader2, RefreshCw, CheckCircle, Trophy } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Button } from "../components/ui/button";
import { Badge } from "../components/ui/badge";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
import { Textarea } from "../components/ui/textarea";
import { Progress } from "../components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../components/ui/tabs";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "../components/ui/select";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter,
} from "../components/ui/dialog";
import {
  getSites, listABTests, createABTest, concludeABTest, generateABVariants,
} from "../lib/api";
import { toast } from "sonner";

export default function ABTesting() {
  const [sites, setSites] = useState([]);
  const [selectedSite, setSelectedSite] = useState("");
  const [tests, setTests] = useState([]);
  const [loading, setLoading] = useState(false);
  const [createOpen, setCreateOpen] = useState(false);
  const [concluding, setConcluding] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [activeTab, setActiveTab] = useState("active");
  const [form, setForm] = useState({ name: "", original: "", variant: "", url_path: "" });
  const [saving, setSaving] = useState(false);

  useEffect(() => { loadSites(); }, []);
  useEffect(() => { if (selectedSite) loadTests(); }, [selectedSite]);

  const loadSites = async () => {
    try {
      const r = await getSites();
      setSites(r.data || []);
      if (r.data?.length) setSelectedSite(r.data[0].id);
    } catch { }
  };

  const loadTests = async () => {
    setLoading(true);
    try {
      const r = await listABTests(selectedSite);
      setTests(Array.isArray(r.data) ? r.data : []);
    } catch (err) {
      toast.error(err.response?.data?.detail || "Failed to load tests");
    } finally { setLoading(false); }
  };

  const handleCreate = async () => {
    if (!form.name || !form.original || !form.variant) return;
    setSaving(true);
    try {
      const r = await createABTest(selectedSite, form);
      setTests(prev => [r.data, ...prev]);
      setCreateOpen(false);
      setForm({ name: "", original: "", variant: "", url_path: "" });
      toast.success("A/B test created");
    } catch (err) {
      toast.error(err.response?.data?.detail || "Failed to create test");
    } finally { setSaving(false); }
  };

  const handleGenerate = async () => {
    if (!form.original) return toast.error("Enter original title/text first");
    setGenerating(true);
    try {
      const r = await generateABVariants(selectedSite, form.original);
      setForm(prev => ({ ...prev, variant: r.data.variant || "" }));
      toast.success("Variant generated by AI");
    } catch (err) {
      toast.error(err.response?.data?.detail || "AI generation failed");
    } finally { setGenerating(false); }
  };

  const handleConclude = async (testId) => {
    setConcluding(testId);
    try {
      const r = await concludeABTest(selectedSite, testId);
      setTests(prev => prev.map(t => t.id === testId ? { ...t, ...r.data, status: "concluded" } : t));
      toast.success(`Test concluded — Winner: ${r.data.winner}`);
    } catch (err) {
      toast.error(err.response?.data?.detail || "Failed to conclude test");
    } finally { setConcluding(null); }
  };

  const activetests = tests.filter(t => t.status !== "concluded");
  const concluded = tests.filter(t => t.status === "concluded");
  const ctr = (t, variant) => {
    const impressions = variant === "A" ? (t.impressions_a || 0) : (t.impressions_b || 0);
    const clicks = variant === "A" ? (t.clicks_a || 0) : (t.clicks_b || 0);
    if (!impressions) return 0;
    return ((clicks / impressions) * 100).toFixed(1);
  };

  const TestCard = ({ t }) => {
    const ctrA = parseFloat(ctr(t, "A"));
    const ctrB = parseFloat(ctr(t, "B"));
    const maxCtr = Math.max(ctrA, ctrB, 1);
    const isActive = t.status !== "concluded";
    return (
      <Card className="content-card">
        <CardContent className="p-4">
          <div className="flex items-start justify-between gap-3 mb-4">
            <div>
              <p className="font-medium text-sm">{t.name}</p>
              <p className="text-xs text-muted-foreground mt-0.5">{t.url_path || "/"}</p>
            </div>
            <div className="flex items-center gap-2">
              <Badge variant="outline" className={`text-xs ${isActive ? "border-emerald-500/30 text-emerald-500" : "border-gray-500/30 text-gray-400"}`}>
                {isActive ? "Running" : "Concluded"}
              </Badge>
              {isActive && (
                <Button variant="outline" size="sm" className="h-6 text-xs"
                  disabled={concluding === t.id}
                  onClick={() => handleConclude(t.id)}>
                  {concluding === t.id ? <Loader2 size={10} className="animate-spin mr-1" /> : <CheckCircle size={10} className="mr-1" />}
                  Conclude
                </Button>
              )}
            </div>
          </div>

          <div className="space-y-3">
            {["A", "B"].map(v => {
              const label = v === "A" ? "Original" : "Variant";
              const text = v === "A" ? t.original : t.variant;
              const c = v === "A" ? ctrA : ctrB;
              const imp = v === "A" ? (t.impressions_a || 0) : (t.impressions_b || 0);
              const isWinner = t.winner === v;
              return (
                <div key={v}>
                  <div className="flex items-center justify-between mb-1">
                    <div className="flex items-center gap-2">
                      <span className={`text-xs font-medium px-1.5 py-0.5 rounded ${v === "A" ? "bg-blue-500/20 text-blue-400" : "bg-purple-500/20 text-purple-400"}`}>{v}</span>
                      <span className="text-xs text-muted-foreground">{label}</span>
                      {isWinner && <Trophy size={10} className="text-yellow-400" />}
                    </div>
                    <div className="text-xs text-muted-foreground">{imp} views · <span className="font-medium">{c}% CTR</span></div>
                  </div>
                  <p className="text-xs text-muted-foreground mb-1 line-clamp-1">{text}</p>
                  <Progress value={(c / maxCtr) * 100} className="h-1.5" />
                </div>
              );
            })}
          </div>
        </CardContent>
      </Card>
    );
  };

  return (
    <div className="page-container">
      <div className="mb-8">
        <motion.h1 className="page-title" initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}>
          A/B Testing
        </motion.h1>
        <motion.p className="page-description" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.1 }}>
          Run split tests on headlines and content, let AI generate variants
        </motion.p>
      </div>

      <div className="flex flex-wrap items-center gap-3 mb-6">
        <Select value={selectedSite} onValueChange={setSelectedSite}>
          <SelectTrigger className="w-[200px]"><SelectValue placeholder="Select site" /></SelectTrigger>
          <SelectContent>{sites.map(s => <SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent>
        </Select>
        <Button onClick={loadTests} variant="outline" size="sm" disabled={!selectedSite}>
          <RefreshCw size={14} className="mr-2" />Refresh
        </Button>
        <Button onClick={() => setCreateOpen(true)} disabled={!selectedSite} size="sm">
          <Plus size={14} className="mr-2" />New Test
        </Button>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-3 gap-4 mb-6">
        {[
          { label: "Running Tests", value: activetests.length },
          { label: "Concluded", value: concluded.length },
          { label: "Total Impressions", value: tests.reduce((a, t) => a + (t.impressions_a || 0) + (t.impressions_b || 0), 0) },
        ].map(s => (
          <Card key={s.label} className="stat-card">
            <p className="stat-value">{s.value}</p>
            <p className="stat-label">{s.label}</p>
          </Card>
        ))}
      </div>

      {loading ? (
        <div className="flex justify-center py-12"><Loader2 size={24} className="animate-spin text-primary" /></div>
      ) : (
        <Tabs value={activeTab} onValueChange={setActiveTab}>
          <TabsList className="mb-4">
            <TabsTrigger value="active">Running ({activetests.length})</TabsTrigger>
            <TabsTrigger value="concluded">Concluded ({concluded.length})</TabsTrigger>
          </TabsList>
          <TabsContent value="active">
            <div className="space-y-3">
              {activetests.map(t => <TestCard key={t.id} t={t} />)}
              {activetests.length === 0 && (
                <div className="text-center py-12 text-muted-foreground text-sm">No active tests — create your first A/B test</div>
              )}
            </div>
          </TabsContent>
          <TabsContent value="concluded">
            <div className="space-y-3">
              {concluded.map(t => <TestCard key={t.id} t={t} />)}
              {concluded.length === 0 && (
                <div className="text-center py-12 text-muted-foreground text-sm">No concluded tests yet</div>
              )}
            </div>
          </TabsContent>
        </Tabs>
      )}

      <Dialog open={createOpen} onOpenChange={setCreateOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>New A/B Test</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <Label className="text-xs mb-1 block">Test Name</Label>
              <Input value={form.name} onChange={e => setForm(p => ({ ...p, name: e.target.value }))} placeholder="Home page headline test" />
            </div>
            <div>
              <Label className="text-xs mb-1 block">URL Path</Label>
              <Input value={form.url_path} onChange={e => setForm(p => ({ ...p, url_path: e.target.value }))} placeholder="/" />
            </div>
            <div>
              <Label className="text-xs mb-1 block">Original (A)</Label>
              <Textarea value={form.original} onChange={e => setForm(p => ({ ...p, original: e.target.value }))}
                placeholder="Your current headline or content..." className="min-h-[80px]" />
            </div>
            <div>
              <div className="flex items-center justify-between mb-1">
                <Label className="text-xs">Variant (B)</Label>
                <Button variant="ghost" size="sm" className="h-6 text-xs text-primary" disabled={generating} onClick={handleGenerate}>
                  {generating ? <Loader2 size={10} className="animate-spin mr-1" /> : <Bot size={10} className="mr-1" />}
                  AI Generate
                </Button>
              </div>
              <Textarea value={form.variant} onChange={e => setForm(p => ({ ...p, variant: e.target.value }))}
                placeholder="Alternative headline or content..." className="min-h-[80px]" />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setCreateOpen(false)}>Cancel</Button>
            <Button onClick={handleCreate} disabled={saving || !form.name || !form.original || !form.variant}>
              {saving ? <Loader2 size={14} className="animate-spin mr-2" /> : null}
              Create Test
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
