import { useState, useEffect, useCallback } from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { Map, RefreshCw, Loader2, ExternalLink, CheckCircle2, FileCode, Info } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Button } from "../components/ui/button";
import { Badge } from "../components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../components/ui/tabs";
import { ScrollArea } from "../components/ui/scroll-area";
import { getSites, getSitemap, getRobotsTxt, listItems } from "../lib/api";

/** Explains where these files come from on a Next.js site and links to the Code workspace. */
function GeneratedByNotice({ siteId, file }) {
  return (
    <div className="mb-4 flex gap-3 rounded-lg border border-primary/20 bg-primary/5 p-3 text-xs text-muted-foreground" role="note">
      <Info size={14} className="mt-0.5 shrink-0 text-primary" aria-hidden="true" />
      <p>
        This view is read-only. On a Next.js site this file is generated by{" "}
        <code className="font-mono text-foreground">{file}</code>. To change it, edit that file in the{" "}
        {siteId ? (
          <Link to={`/sites/${siteId}/code`} className="text-primary underline">Code workspace</Link>
        ) : (
          "Code workspace"
        )}
        , which creates a change set for review, validation and approval.
      </p>
    </div>
  );
}

export default function SitemapRobots() {
  const [sites, setSites] = useState([]);
  const [selectedSite, setSelectedSite] = useState("");

  // Sitemap state
  const [sitemap, setSitemap] = useState(null);
  const [loadingSitemap, setLoadingSitemap] = useState(false);

  // Robots.txt state
  const [robotsContent, setRobotsContent] = useState("");
  const [robotsUrl, setRobotsUrl] = useState("");
  const [loadingRobots, setLoadingRobots] = useState(false);

  useEffect(() => {
    getSites().then(r => {
      const list = listItems(r.data);
      setSites(list);
      if (list.length > 0) setSelectedSite(list[0].id);
    }).catch(() => {});
  }, []);

  const loadSitemap = useCallback(async () => {
    if (!selectedSite) return;
    setLoadingSitemap(true);
    try {
      const r = await getSitemap(selectedSite);
      setSitemap(r.data);
    } catch { setSitemap(null); }
    finally { setLoadingSitemap(false); }
  }, [selectedSite]);

  const loadRobots = useCallback(async () => {
    if (!selectedSite) return;
    setLoadingRobots(true);
    try {
      const r = await getRobotsTxt(selectedSite);
      setRobotsContent(r.data?.content || "");
      setRobotsUrl(r.data?.url || "");
    } catch { setRobotsContent(""); setRobotsUrl(""); }
    finally { setLoadingRobots(false); }
  }, [selectedSite]);

  useEffect(() => {
    loadSitemap();
    loadRobots();
  }, [loadSitemap, loadRobots]);

  return (
    <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Sitemap & Robots.txt</h1>
          <p className="text-sm text-muted-foreground mt-1">Inspect the sitemap and robots.txt your site serves</p>
        </div>
        <Select value={selectedSite} onValueChange={setSelectedSite}>
          <SelectTrigger className="w-44" aria-label="Site"><SelectValue placeholder="Select site" /></SelectTrigger>
          <SelectContent>{sites.map(s => <SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent>
        </Select>
      </div>

      <Tabs defaultValue="sitemap">
        <TabsList>
          <TabsTrigger value="sitemap">Sitemap</TabsTrigger>
          <TabsTrigger value="robots">robots.txt</TabsTrigger>
        </TabsList>

        <TabsContent value="sitemap" className="space-y-4 mt-4">
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between flex-wrap gap-2">
                <CardTitle className="flex items-center gap-2">
                  <Map size={18} className="text-primary" />
                  Sitemap URLs
                  {sitemap?.total != null && (
                    <Badge variant="secondary">{sitemap.total} URLs</Badge>
                  )}
                </CardTitle>
                <div className="flex gap-2">
                  {sitemap?.sitemap_url && (
                    <Button variant="outline" size="sm" asChild>
                      <a href={sitemap.sitemap_url} target="_blank" rel="noopener noreferrer">
                        <ExternalLink size={13} className="mr-1" aria-hidden="true" /> View
                      </a>
                    </Button>
                  )}
                  <Button variant="outline" size="sm" onClick={loadSitemap} disabled={loadingSitemap || !selectedSite}>
                    {loadingSitemap ? <Loader2 size={13} className="animate-spin" /> : <RefreshCw size={13} className="mr-1" />}
                    Reload
                  </Button>
                  {selectedSite && (
                    <Button variant="outline" size="sm" asChild>
                      <Link to={`/sites/${selectedSite}/code`}>
                        <FileCode size={13} className="mr-1" aria-hidden="true" /> Edit app/sitemap.ts
                      </Link>
                    </Button>
                  )}
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <GeneratedByNotice siteId={selectedSite} file="app/sitemap.ts" />
              <p className="mb-3 text-xs text-muted-foreground">
                To submit the sitemap to Google Search Console, use the{" "}
                <Link to="/indexing-tracker" className="text-primary underline">Indexing Tracker</Link>.
              </p>
              {loadingSitemap ? (
                <div className="flex justify-center py-8"><Loader2 size={24} className="animate-spin text-muted-foreground" /></div>
              ) : sitemap?.message ? (
                <div className="text-center py-8 text-muted-foreground text-sm">{sitemap.message}</div>
              ) : (
                <>
                  {sitemap?.sitemap_url && (
                    <div className="mb-3 flex items-center gap-2 text-sm">
                      <CheckCircle2 size={14} className="text-emerald-500" aria-hidden="true" />
                      <span className="text-muted-foreground">Sitemap found at:</span>
                      <a href={sitemap.sitemap_url} target="_blank" rel="noopener noreferrer"
                        className="text-primary hover:underline truncate">{sitemap.sitemap_url}</a>
                    </div>
                  )}
                  <ScrollArea className="h-64">
                    <ul className="space-y-1">
                      {(sitemap?.urls || []).map((url, i) => (
                        <li key={i}>
                          <a href={url} target="_blank" rel="noopener noreferrer"
                            className="text-xs text-muted-foreground hover:text-primary hover:underline flex items-center gap-1">
                            <ExternalLink size={10} aria-hidden="true" />{url}
                          </a>
                        </li>
                      ))}
                    </ul>
                  </ScrollArea>
                </>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="robots" className="space-y-4 mt-4">
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between flex-wrap gap-2">
                <CardTitle className="text-base">robots.txt</CardTitle>
                <div className="flex gap-2">
                  {robotsUrl && (
                    <Button variant="outline" size="sm" asChild>
                      <a href={robotsUrl} target="_blank" rel="noopener noreferrer">
                        <ExternalLink size={13} className="mr-1" aria-hidden="true" /> View live
                      </a>
                    </Button>
                  )}
                  <Button variant="outline" size="sm" onClick={loadRobots} disabled={loadingRobots || !selectedSite} aria-label="Reload robots.txt">
                    <RefreshCw size={13} className={loadingRobots ? "animate-spin" : ""} />
                  </Button>
                  {selectedSite && (
                    <Button variant="outline" size="sm" asChild>
                      <Link to={`/sites/${selectedSite}/code`}>
                        <FileCode size={13} className="mr-1" aria-hidden="true" /> Edit app/robots.ts
                      </Link>
                    </Button>
                  )}
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <GeneratedByNotice siteId={selectedSite} file="app/robots.ts" />
              {loadingRobots ? (
                <div className="flex justify-center py-8"><Loader2 size={24} className="animate-spin text-muted-foreground" /></div>
              ) : robotsContent ? (
                <pre
                  className="bg-muted/30 border border-border/40 rounded-lg p-3 text-xs font-mono whitespace-pre-wrap overflow-x-auto max-h-[400px] overflow-y-auto"
                  aria-label="robots.txt content"
                  tabIndex={0}
                >
                  {robotsContent}
                </pre>
              ) : (
                <div className="text-center py-8 text-muted-foreground text-sm">
                  No robots.txt was found for this site.
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </motion.div>
  );
}
